version: '3'
services:

  # The Application Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: diegoribeiro/php
    container_name: app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network

  # The Nginx Service
  nginx_service:
    image: nginx:1.15.8-alpine
    container_name: nginx_service
    restart: unless-stopped
    tty: true
    ports:
      - "8000:80"
      - "8443:443"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network

  # The MySQL Service
  mysql_service:
    image: mysql:5.7.25
    container_name: mysql_service
    restart: unless-stopped
    tty: true
    ports:
      - "3360:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - dbdata:/var/lib/mysql/
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - app-network

# Docker Networks
networks:
  app-network:
    driver: bridge

# Volumes
volumes:
  dbdata:
    driver: local
